### ISSUE TITLE
Would you upload the q2_NER.py?

### ISSUE THREAD

**Issue by shizi626** [Krishnkant-Swarnkar/CS224d-Assignment-Solutions#2]
I have some problem in this file and can't find why my code running so weird.

**Comment by Krishnkant-Swarnkar** [comment]
Please find the solutions(uploaded) to q2_NER.py 
Hope this helps .
Please feel free to ask for further queries :-)

**Comment by shizi626** [comment]
thanks a lot! BTW, I have solved that problem yesterday~
